In [1]:
import numpy as np
import pandas as pd

# Модель для прогнозирования, например ARIMA
from sktime.forecasting.arima import ARIMA
# Визуализация временных рядов
from sktime.utils.plotting import plot_series
# Модули для кросс-валидации
from sktime.split import temporal_train_test_split, ExpandingWindowSplitter, SlidingWindowSplitter, SingleWindowSplitter
from sktime.forecasting.model_evaluation import evaluate
from sktime.performance_metrics.forecasting import MeanSquaredError, MeanAbsoluteError, MeanAbsolutePercentageError # Метрики MSE, MAE, MAPE

import pandas_datareader.data as web

# настройки визуализации
import matplotlib.pyplot as plt

# Не показывать Warnings
import warnings
warnings.simplefilter(action='ignore', category=Warning)
# Не показывать ValueWarning, ConvergenceWarning из statsmodels
from statsmodels.tools.sm_exceptions import ValueWarning, ConvergenceWarning
warnings.simplefilter('ignore', category=ValueWarning)
warnings.simplefilter('ignore', category=ConvergenceWarning)

In [2]:
y = np.log(web.DataReader(name='GDP', data_source='fred', start='1995-01-01'))
y.index = y.index.to_period(freq='Q')
# длина ряда
len(y)

120

In [3]:
forecaster = ARIMA(order=(1,0,1), trend='ct')

cv_strategy = SingleWindowSplitter(fh=np.arange(1, 11), window_length=110)

# инициализируем метрики
metric = [MeanSquaredError(square_root=False), MeanAbsoluteError(), MeanAbsolutePercentageError()]

cv_res = evaluate(forecaster=forecaster, y=y, cv=cv_strategy, strategy="refit", return_data=False, scoring=metric)
cv_res

,test_MeanSquaredError,test_MeanAbsoluteError,test_MeanAbsolutePercentageError,fit_time,pred_time,len_train_window,cutoff
0,0.00298,0.050684,0.004941,0.551495,0.010757,110,2022Q2

In [4]:
forecaster = ARIMA(order=(1,1,0), trend='c')

cv_strategy = SingleWindowSplitter(fh=np.arange(1, 11), window_length=110)

# инициализируем метрики
metric = [MeanSquaredError(square_root=False), MeanAbsoluteError(), MeanAbsolutePercentageError()]

cv_res = evaluate(forecaster=forecaster, y=y, cv=cv_strategy, strategy="refit", return_data=False, scoring=metric)
cv_res

,test_MeanSquaredError,test_MeanAbsoluteError,test_MeanAbsolutePercentageError,fit_time,pred_time,len_train_window,cutoff
0,0.000521,0.021771,0.002123,0.038296,0.010718,110,2022Q2

In [6]:
forecaster = ARIMA(order=(1,0,1), trend='ct')

cv_strategy = SlidingWindowSplitter(fh=np.arange(1, 6), initial_window=80, step_length=1)

# инициализируем метрики
metric = [MeanSquaredError(square_root=False), MeanAbsoluteError(), MeanAbsolutePercentageError()]

cv_res = evaluate(forecaster=forecaster, y=y, cv=cv_strategy, strategy="refit", return_data=False, scoring=metric)
cv_res

,test_MeanSquaredError,test_MeanAbsoluteError,test_MeanAbsolutePercentageError,fit_time,pred_time,len_train_window,cutoff
0,0.000456,0.017357,0.001767,0.139841,0.008613,80,2014Q4
1,0.000235,0.012614,0.001283,0.129532,0.008407,10,2015Q1
2,0.000350,0.017254,0.001755,0.122698,0.008377,10,2015Q2
3,0.000360,0.018760,0.001907,0.132433,0.008357,10,2015Q3
4,0.000220,0.014554,0.001478,0.090716,0.008354,10,2015Q4
5,0.000050,0.006910,0.000701,0.058031,0.008462,10,2016Q1
6,0.000008,0.002459,0.000249,0.073341,0.008212,10,2016Q2
7,0.000091,0.007349,0.000743,0.097579,0.008462,10,2016Q3
8,0.000181,0.010422,0.001052,0.081100,0.008234,10,2016Q4
9,0.000116,0.008770,0.000884,0.099168,0.008458,10,2017Q1
10,0.000298,0.015884,0.001600,0.108750,0.008239,10,2017Q2
11,0.000442,0.020703,0.002084,0.151129,0.008397,10,2017Q3
12,0.000046,0.006234,0.000627,0.076890,0.008237,10,2017Q4
13,0.000012,0.003310,0.000333,0.150409,0.008405,10,2018Q1
14,0.000281,0.015441,0.001549,0.209381,0.008228,10,2018Q2
15,0.000157,0.012235,0.001227,0.138655,0.008441,10,2018Q3
16,0.000265,0.011441,0.001146,0.073416,0.008210,10,2018Q4
17,0.003898,0.036482,0.003677,0.118430,0.008963,10,2019Q1
18,0.004209,0.044690,0.004498,0.121230,0.008219,10,2019Q2
19,0.004937,0.056420,0.005671,0.122606,0.008419,10,2019Q3
20,0.004019,0.052585,0.005283,0.125158,0.008458,10,2019Q4
21,0.002862,0.038836,0.003905,0.045639,0.008383,10,2020Q1
22,0.003192,0.047565,0.004731,0.127436,0.008215,10,2020Q2
23,0.007647,0.079213,0.007861,0.128473,0.008380,10,2020Q3
24,0.009229,0.089942,0.008906,0.103096,0.008213,10,2020Q4
25,0.011223,0.101712,0.010050,0.104092,0.008407,10,2021Q1
26,0.007109,0.081123,0.007998,0.038106,0.008223,10,2021Q2
27,0.004108,0.062866,0.006187,0.089658,0.008374,10,2021Q3
28,0.001584,0.039571,0.003888,0.124207,0.008324,10,2021Q4
29,0.000256,0.013951,0.001369,0.103726,0.008504,10,2022Q1
30,0.002733,0.049672,0.004863,0.146460,0.008185,10,2022Q2
31,0.004679,0.056757,0.005545,0.114834,0.008353,10,2022Q3
32,0.006783,0.073817,0.007205,0.115624,0.008182,10,2022Q4
33,0.010632,0.096984,0.009456,0.132718,0.008359,10,2023Q1
34,0.001747,0.036532,0.003556,0.118107,0.008273,10,2023Q2
35,0.001284,0.032318,0.003143,0.124660,0.008377,10,2023Q3

In [7]:

# средняя MSE, MAE, MAPE
cv_res.iloc[:,:len(metric)].mean()

test_MeanSquaredError               0.002658
test_MeanAbsoluteError              0.035909
test_MeanAbsolutePercentageError    0.003560
dtype: float64

In [8]:
# Зададим список из специфицированных моделей прогнозирования
forecasters = [ARIMA(order=(1,0,1), trend='ct'), ARIMA(order=(1,1,0), trend='c'), ARIMA(order=(1,1,1), trend='n'), ARIMA(order=(1,2,0), trend='n')]

# специфицируем метод кросс-валидации. Например, SlidingWindowSplitter
cv_strategy = SlidingWindowSplitter(fh=np.arange(1, 6), initial_window=80, step_length=1)

# инициализируем метрики
metric = [MeanSquaredError(square_root=False), MeanAbsoluteError(), MeanAbsolutePercentageError()]

# датафрейм с метриками по столбцам
cv_data = pd.DataFrame(data=None, columns=['MSE', 'MAE', 'MAPE'])

for model in forecasters:
	print(model)
	cv_res = evaluate(forecaster=model, y=y, cv=cv_strategy, strategy="refit", return_data=False, scoring=metric)
	# print(df.iloc[:,:len(metric)].mean()) # метрики для каждой модели
	cv_data.loc[len(cv_data.index)] = cv_res.iloc[:,[0,1,2]].mean().values

# результаты кросс-валидации в виде датафрейма
cv_data

ARIMA(order=(1, 0, 1), trend='ct')
ARIMA(order=(1, 1, 0), trend='c')
ARIMA(order=(1, 1, 1), trend='n')
ARIMA(order=(1, 2, 0), trend='n')

        MSE       MAE      MAPE
0  0.002658  0.035909  0.003560
1  0.003601  0.031448  0.003127
2  0.005739  0.040858  0.004059
3  0.021456  0.041858  0.004171

In [9]:
# Индекс модели
for i in range(cv_data.shape[1]):
	print(f'{cv_data.columns[i]}: model #={cv_data.iloc[:,i].argmin()}')

MSE: model #=0
MAE: model #=1
MAPE: model #=1

In [10]:
# Зададим список из специфицированных моделей прогнозирования
forecasters = [ARIMA(order=(1,0,1), trend='ct'), ARIMA(order=(1,1,0), trend='c'), ARIMA(order=(1,1,1), trend='n'), ARIMA(order=(1,2,0), trend='n')]

# специфицируем метод кросс-валидации. Например, SlidingWindowSplitter
cv_strategy = ExpandingWindowSplitter(fh=np.arange(1, 6), initial_window=80, step_length=1)

# инициализируем метрики
metric = [MeanSquaredError(square_root=False), MeanAbsoluteError(), MeanAbsolutePercentageError()]

# датафрейм с метриками по столбцам
cv_data = pd.DataFrame(data=None, columns=['MSE', 'MAE', 'MAPE'])

for model in forecasters:
	print(model)
	cv_res = evaluate(forecaster=model, y=y, cv=cv_strategy, strategy="refit", return_data=False, scoring=metric)
	# print(df.iloc[:,:len(metric)].mean()) # метрики для каждой модели
	cv_data.loc[len(cv_data.index)] = cv_res.iloc[:,[0,1,2]].mean().values

# результаты кросс-валидации в виде датафрейма
cv_data

ARIMA(order=(1, 0, 1), trend='ct')
ARIMA(order=(1, 1, 0), trend='c')
ARIMA(order=(1, 1, 1), trend='n')
ARIMA(order=(1, 2, 0), trend='n')

        MSE       MAE      MAPE
0  0.001791  0.028439  0.002831
1  0.003390  0.025859  0.002575
2  0.004383  0.028392  0.002829
3  0.005903  0.030223  0.003013

In [11]:
# Индекс модели
for i in range(cv_data.shape[1]):
	print(f'{cv_data.columns[i]}: model #={cv_data.iloc[:,i].argmin()}')

MSE: model #=0
MAE: model #=1
MAPE: model #=1

In [12]:
# Зададим список из специфицированных моделей прогнозирования
forecasters = [ARIMA(order=(1,0,1), trend='ct'), ARIMA(order=(1,1,0), trend='c'), ARIMA(order=(1,1,1), trend='n'), ARIMA(order=(1,2,0), trend='n')]

# специфицируем метод кросс-валидации. Например, SlidingWindowSplitter
cv_strategy = SingleWindowSplitter(fh=np.arange(1, 11), window_length=110)

# инициализируем метрики
metric = [MeanSquaredError(square_root=False), MeanAbsoluteError(), MeanAbsolutePercentageError()]

# датафрейм с метриками по столбцам
cv_data = pd.DataFrame(data=None, columns=['MSE', 'MAE', 'MAPE'])

for model in forecasters:
	print(model)
	cv_res = evaluate(forecaster=model, y=y, cv=cv_strategy, strategy="refit", return_data=False, scoring=metric)
	# print(df.iloc[:,:len(metric)].mean()) # метрики для каждой модели
	cv_data.loc[len(cv_data.index)] = cv_res.iloc[:,[0,1,2]].mean().values

# результаты кросс-валидации в виде датафрейма
cv_data

ARIMA(order=(1, 0, 1), trend='ct')
ARIMA(order=(1, 1, 0), trend='c')
ARIMA(order=(1, 1, 1), trend='n')
ARIMA(order=(1, 2, 0), trend='n')

        MSE       MAE      MAPE
0  0.002980  0.050684  0.004941
1  0.000521  0.021771  0.002123
2  0.000418  0.019466  0.001898
3  0.001522  0.032290  0.003145

In [13]:
# Индекс модели
for i in range(cv_data.shape[1]):
	print(f'{cv_data.columns[i]}: model #={cv_data.iloc[:,i].argmin()}')

MSE: model #=2
MAE: model #=2
MAPE: model #=2